# Generated by Django 3.0.8 on 2020-10-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('PRODUCTS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('phone_type', models.CharField(choices=[('Android', 'Android'), ('iPhone', 'iPhone'), ('Feature Phone', 'Feature Phone'), ('Tablet', 'Tablet')], max_length=50)),
                ('RAM', models.IntegerField()),
                ('internal_storage', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.Product')),
            ],
        ),
    ]
