# Generated by Django 3.0.8 on 2020-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PHONES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedetails',
            name='RAM',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='phonedetails',
            name='internal_storage',
            field=models.IntegerField(default=32),
        ),
    ]
