# Generated by Django 3.0.8 on 2020-10-11 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('PHONES', '0002_auto_20201011_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonedetails',
            options={'verbose_name_plural': 'Phones'},
        ),
    ]
