# Generated by Django 3.0.8 on 2020-10-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='delivery_address_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='delivery_address_2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(default='Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='City', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landmark',
            field=models.CharField(default='landmark', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(default='450331', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='state', max_length=150),
            preserve_default=False,
        ),
    ]
