# Generated by Django 3.0.8 on 2020-10-14 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('USER', '0002_auto_20201013_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Address',
            new_name='address',
        ),
    ]
