# Generated by Django 3.0.8 on 2020-10-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCTS', '0002_auto_20201012_1731'),
        ('USER', '0003_auto_20201012_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercart',
            name='cart_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PRODUCTS.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
