# Generated by Django 3.0.8 on 2020-10-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('SELLER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.Category')),
            ],
            options={
                'db_table': 'tbl_product_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_stoke', models.IntegerField()),
                ('product_MRP', models.IntegerField()),
                ('product_selling_price', models.IntegerField()),
                ('product_home_img', models.ImageField(upload_to='products_homepage_images')),
                ('is_product_live', models.BooleanField(default=False)),
                ('is_product_verified', models.BooleanField(default=False)),
                ('product_add_datetime_stamp', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.Category')),
                ('product_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SELLER.Shop')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.ProductType')),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
