# Generated by Django 3.0.8 on 2020-10-12 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('PRODUCTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
